# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ersin Özben
title: Junior Software Developer
email: ersinoezben@icloud.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  42sin
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: ersin-özben-789265273
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hey, my name's Ersin and I'm a Junior Software Developer with a passion for back-end development.
  At 22, I recently completed the Core Curriculum at [42 Heilbronn](https://www.42heilbronn.de), showing my commitment to continous learning and growth in this field.

  My primary expertise lies in <mark>C/C++</mark>, but I've also delved into diverse technologies such as:

  <mark>JavaScript</mark>,<mark>NestJS</mark>,<mark>AngularJS</mark>,<mark>Docker</mark>,<mark>Docker</mark>,<mark>Bash</mark> and system administration in general.

  Through these experiences, I've honed my technological skills and am now ready for the exciting challenges the business world has to offer.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: My own bash-like Shell
        link: github.com/42sin/minishell
        additional_links:
          - title: 42sin/minishell
            icon: fab fa-github
            url: github.com/42sin/minishell
        quote: >
          As beautiful as a shell
        description: |
          The first group project during my time at 42, as well as the first huge project that we had to handle. This was by far my favourite project during the curriculum and the one that teached me the most. I gained knowledge about: how the CPU works in general, memory management, algorithms, general use of C, data structures and more.
      - layout: top-middle
        title: IRC Server in C++
        link: github.com/42sin/ft_irc
        # link_text: Project Website
        additional_links:
          - title:  42sin/ft_irc
            icon: fab fa-github
            url: github.com/42sin/ft_irc
        quote: >
          Based on the RFC 2812
        description: |
          This was one of the first big projects in C++. It gave me an opportunity to enhance my skills in object-oriented programming, C++ and things about networking/server in general.
      - layout: top-middle
        title: Graphics project inspired by Wolfenstein 3D
        link: github.com/42sin/cub3d
        additional_links:
          - title: 42sin/cub3d
            icon: fab fa-github
            url: github.com/42sin/cub3d
        quote: >
          Exploring ray-tracing in C
        description: |
          The second group project and the last project that was in pure C. It allowed me to work with an extern library for the first time, teached me more about algorithms and how mathematics can help when working with graphical projects.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Christiane-Herzog-Gymnasium
        caption: Heilbronn, 2017 - 2020
        sub_title: Abitur/high school graduation
        description: | # this will include new lines to allow paragraphs
          This was my first in-depth contact with computer science, we learned Java and I really enjoyed it.
          It was my best subject with mathematics.
      - layout: left
        title: 42 Heilbronn
        caption: 2021 - today
        sub_title: Software Development University
        description: |
          A challenging new approach of learning Computer Science. The main languages learned are C/C++ and JavaScript but we also learned a lot about system administration.

  - title: Languages
    layout: list
    content:
      - layout: top-middle
        title: German
        sub_title: Native
      - layout: top-middle
        title: English
        sub_title: Full professional proficiency (C1)
      - layout: top-middle
        title: Turkish
        sub_title: Fluently (B2)

# Footer
footer_show_references: true
references_title: Contact

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
